### ISSUE TITLE
OpenRPC prefixes?

### ISSUE THREAD

**Issue by ukstv** [NodeFactoryIo/filsnap#67]
Hey, guys, what do you think on prefixing OpenRPC-like methods with "fil_" prefix, so that it is unified (of sorts) with Ethereum providers?

**Comment by ukstv** [comment]
cc @Schwartz10 as an author of the Filecoin Wallet provider package (https://github.com/openworklabs/filecoin-wallet-provider)

**Comment by MakMuftic** [comment]
@ukstv This is actually a good idea, I will prefix methods with `fil_`
