### ISSUE TITLE
Block Explorer URL Incorrect

### ISSUE THREAD

**Issue by rekmarks** [NodeFactoryIo/filsnap#69]
The https://filscan.io FIL address path has changed.

When clicking the asset in the MetaMask UI, filsnap currently redirects to: `https://filscan.io/#/address/detail?address=ADDRESS`

While the correct path is: `https://filscan.io/#/tipset/address-detail?address=ADDRESS`

**Comment by rekmarks** [comment]
As an additional note, maybe it would be better to direct the user to the Netlify Snap UI, since it's more interactive.

**Comment by MakMuftic** [comment]
@rekmarks Thanks for the issue. I think it is more meaningful to keep the link on the Filscan address details. Netlify Snap UI is more of a demo app for _FilSnap_ while Filscan shows transaction history for the specified address.
